java_test(
    name = "hmac-md5-test",
    size = "small",
    srcs = ["src/com/yhsif/onepwd/HmacMd5Test.java"],
    test_class = "com.yhsif.onepwd.HmacMd5Test",
    deps = [
        "//:hmac-md5",
        "@com_google_guava_guava//jar",
        "@com_google_truth_truth//jar",
        "@junit_junit//jar",
        "@org_hamcrest_hamcrest_core//jar",
    ],
)
