# vim:ft=python:noet:ts=8:sw=8

# Download it yourself at:
# http://search.maven.org/#artifactdetails%7Corg.hamcrest%7Chamcrest-core%7C1.3%7Cjar
prebuilt_jar(
	name = 'hamcrest-core',
	binary_jar = 'hamcrest-core-1.3.jar',
)

# Download it yourself at:
# http://search.maven.org/#artifactdetails%7Cjunit%7Cjunit%7C4.12%7Cjar
prebuilt_jar(
	name = 'junit',
	binary_jar = 'junit-4.12.jar',
	deps = [
		':hamcrest-core',
	],
	visibility = [
		'//tests:',
	],
)
