# vim:ft=python:et:ts=2:sw=2

java_test(
  name = 'hmac-md5-test',
  srcs = ['src/com/yhsif/onepwd/HmacMd5Test.java'],
  size = "small",
  test_class = "com.yhsif.onepwd.HmacMd5Test",
  deps = [
    '@com_google_truth_truth//jar',
    '@com_google_guava_guava//jar',
    '@junit_junit//jar',
    '@org_hamcrest_hamcrest_core//jar',
    '//java:hmac-md5',
  ],
)
